### ISSUE TITLE
how to build in visual studio?

### ISSUE THREAD

**Issue by gooddawn69174s1** [bbangg/enet-socks5#1]

**Comment by bbangg** [comment]
Can you provide some details? Are you encountering any errors, or do you simply need help with the compiling?

**Comment by gooddawn69174s1** [comment]
![image](https://github.com/bbangg/enet-socks5/assets/129963098/f705838d-b359-4d86-9bc5-ec735f8e8eae)

**Comment by gooddawn69174s1** [comment]
![image](https://github.com/bbangg/enet-socks5/assets/129963098/eb43ee36-c655-42d9-a8d5-953b01fd1b2a)

**Comment by bbangg** [comment]
I haven't personally tested the project on Windows (Visual Studio) yet. I'm using CMake to set up the project, and some header files might differ on Windows.

If you encounter an error such as "cannot convert 'const in6_addr' to ULONG," it indicates a type conversion issue. The error is likely occurring due to differences in data types between platforms. The in6_addr structure on Windows is used to represent an IPv6 address, while ULONG is an unsigned long data type.

```cpp
#if defined(_WIN32)
#if defined(_MSC_VER) && defined(ENET_IMPLEMENTATION)
#pragma warning(disable : 4267) // size_t to int conversion
#pragma warning(disable : 4244) // 64bit to 32bit int
#pragma warning(disable : 4018) // signed/unsigned mismatch
#pragma warning(disable : 4146) // unary minus operator applied to unsigned type
// ...
#else
#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <poll.h>
#include <arpa/inet.h>
#include <netinet/in.h>
// ...
#endif
```

**Compiler Settings**: Verify that your Visual Studio project settings are correctly configured and there are no specific compiler flags causing the issue.

I don't have plan and time to test/release it for windows for now.
